Repository wecode-bootcamp-korea/28-2nd-mycodetrip-frontend, pull requests merged in 2022-01, with the labels that each got.

#2 [28기 강희원][Add] 항공권 검색바 - 출발 및 도착 & 도시 선택 모달 레이아웃 구성 / 리뷰 반영
  package-lock.json
  package.json
  public/data/main/searchedTickets.json
  src/components/FlightsSearch/FlightsSearch.js
  src/components/RouteSearch/RouteSearch.js
  src/components/SelectCities/SelectCities.js
  src/config/config.js
  src/index.js
  src/pages/Main/CarouselSlick/CarouselSlick.js
  src/pages/Main/Main.js
  src/pages/Main/SearchedTickets/SearchedTickets.js
Labels: Status: 리뷰 요청

#5 [28기 강희원][Add] 최저가 항공권 리스트 레이아웃, mock data 생성
  public/data/main/cheapFlightsData.json
  src/config/config.js
  src/pages/Main/CarouselSlick/CarouselSlick.js
  src/pages/Main/CheapFlights/CheapFlights.js
  src/pages/Main/Main.js
  src/pages/Main/SearchedTickets/SearchedTickets.js
Labels: Status: 리뷰 요청

#6 [28기 강희원][Add] 검색바 > 출발 및 도착지 도시 선택 모달 구현, 리뷰 반영
  public/data/main/cheapFlightsData.json
  public/data/main/searchedTickets.json
  src/components/RouteSearch/RouteSearch.js
  src/components/SelectCities/SelectCities.js
  src/pages/Main/CarouselSlick/CarouselSlick.js
  src/pages/Main/CheapFlights/CheapFlights.js
  src/pages/Main/SearchedTickets/SearchedTickets.js
Labels: Status: 리뷰 요청

#1 [ 28기 박준영 ] FlightCheck페이지 추가 및 useQueryString 기능 추가
  package-lock.json
  public/data/flights/airlineOption.json
  public/data/flights/flightData.json
  public/data/flights/flightDetail.json
  public/data/flights/seatOption.json
  public/images/FlightLoading.jpg
  src/components/FlightInfoCard/FlightBadge.js
  src/components/FlightInfoCard/FlightInfoCard.js
  src/hooks/useFetch.js
  src/hooks/useQueryString.js
  src/pages/FlightsCheck/FlightsCheck.js
  src/pages/FlightsList/FlightsList.js
  src/pages/FlightsList/components/FlightFilter.js
  src/pages/FlightsList/components/FlightPriceRange.js
  src/utils/getTime.js
Labels: Status: 리뷰 요청

#7 [28기 강희원][Add] 출발 및 도착 도시 선택 모달 > 도시 선택시 input 반영, 인원 좌석 레이아웃
  public/data/flightsSearchBar/flightsSearchBar.json
  src/components/FlightsSearch/FlightsSearch.js
  src/components/FlightsSearchBar/FlightsSearchBar.js
  src/components/FlightsSearchBar/Passengers/Passengers.js
  src/components/FlightsSearchBar/RouteSearch/RouteSearch.js
  src/components/Modals/SelectCities/SelectCities.js
  src/components/Modals/SelectPassenger/SelectPassenger.js
  src/config/config.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#8 [28기 강희원][Add] 승객 인원 및 좌석 구현, date picker, 최저가 항공권 mock data 수정 및 컴포넌트 재사용
  package-lock.json
  package.json
  public/data/main/cheapFlightsData.json
  public/data/main/cheapTicketsData.json
  src/components/FlightsSearchBar/DatePick/DatePick.js
  src/components/FlightsSearchBar/FlightsSearchBar.js
  src/components/FlightsSearchBar/Passengers/Passengers.js
  src/components/FlightsSearchBar/RouteSearch/RouteSearch.js
  src/components/Modals/SelectPassenger/SelectPassenger.js
  src/config/config.js
  src/pages/Main/CheapFlights/CheapFlights.js
  src/pages/Main/SearchedTickets/SearchedTickets.js
Labels: Status: 리뷰 요청

#10 [28기 박준영] 예약한 항공권을 확인할 수 있는 마이페이지 추가
  public/data/flights/flightDetail.json
  public/data/myPage/reservedFlight.json
  public/data/myPage/reservedUserInfo.json
  src/Router.js
  src/components/FlightInfoCard/FlightBadge.js
  src/components/FlightInfoCard/FlightInfoCard.js
  src/components/FlightInfoCard/FlightTimeInfo.js
  src/components/ReservedFlightTable/ReservedFlightTable.js
  src/pages/MyPage/Mypage.js
  src/pages/MyPage/ReservationSummaryCard.js
  src/styles/GlobalStyle.js
  src/utils/getTime.js
Labels: Status: Accepted

#3 [28기 성윤경] ADD:Info input창 유효성 조건 확인 구현, aside 구현, back-end와 통신 진행중
  package-lock.json
  public/data/main/cheapFlightsData.json
  src/components/FlightInfoCard/FlightInfoCard.js
  src/components/FlightsSearchBar/Passengers/Passengers.js
  src/config/config.js
  src/pages/Reservation/BookerInfo.js
  src/pages/Reservation/PassengerInfo.js
  src/pages/Reservation/PassengerInfos.js
  src/pages/Reservation/ReservAside.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/ReservedTicketInfo.js
  src/pages/Reservation/components/Button.js
  src/pages/Reservation/components/Input.js
  src/pages/Reservation/components/InputWrapper.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#9 [28기 김선주]Feature/auth 로그인 작동 구현중 로그아웃 마무리중
  public/images/Logo_main.png
  public/index.html
  src/components/Navbar/Navbar.js
  src/index.js
  src/pages/Auth/Auth.js
  src/pages/Auth/Kakao.js
  src/pages/Auth/OAuth.js
Labels: Status: Conflict 해결 요청, Status: 추가 기능 구현중, Status: Rebase 요청

#12 [28기 강희원][Add] 최저가 항공권 & 도시 데이터 백엔드 통신 완료, footer
  src/components/Footer/Footer.js
  src/config/config.js
  src/pages/Main/CheapFlights/CheapFlights.js
Labels: Status: 리뷰 요청

#13 [28기 성윤경]Fix : conflict 해결
  package-lock.json
  public/index.html
  src/components/FlightInfoCard/FlightInfoCard.js
  src/components/FlightsSearchBar/Passengers/Passengers.js
  src/components/ReservedFlightTable/ReservedFlightTable.js
  src/config/config.js
  src/pages/Auth/Auth.js
  src/pages/Reservation/PassengerInfo.js
  src/pages/Reservation/PassengerInfos.js
  src/pages/Reservation/ReservAside.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/ReservedTicketInfo.js
  src/pages/Reservation/components/Button.js
Labels: Status: Accepted

#14 [28기 박준영] 항공권 리스트 페이지 로딩 페이지 추가 구현
  src/components/FlightInfoCard/FlightInfoCard.js
  src/components/ReservedFlightTable/ReservedFlightTable.js
  src/config/config.js
  src/hooks/useQueryString.js
  src/pages/FlightsList/FlightsList.js
  src/pages/FlightsList/components/FlightLoading.js
Labels: Status: 리뷰 요청

#15 [28기 강희원][Fix] 리뷰 반영, 최근 검색한 항공권 분기 처리 및 로컬스토리지 연결
  src/components/FlightsSearchBar/DatePick/DatePick.js
  src/components/FlightsSearchBar/FlightsSearchBar.js
  src/components/Modals/SelectCities/SelectCities.js
  src/components/Modals/SelectPassenger/SelectPassenger.js
  src/index.js
  src/pages/Main/SearchedTickets/SearchedTickets.js
Labels: Status: Accepted

#17 [28기 강희원][Modify] 검색바 쿼리 버그 수정, 최저가 항공권 navigate 연결, 배너 이미지 추가
  public/images/banners/banner_0.png
  public/images/banners/banner_1.png
  public/images/banners/banner_2.png
  public/images/banners/banner_3.png
  src/components/FlightsSearchBar/FlightsSearchBar.js
  src/components/FlightsSearchBar/Passengers/Passengers.js
  src/components/FlightsSearchBar/RouteSearch/RouteSearch.js
  src/components/Modals/SelectCities/SelectCities.js
  src/components/Modals/SelectPassenger/SelectPassenger.js
  src/pages/Main/CarouselSlick/CarouselSlick.js
  src/pages/Main/CheapFlights/CheapFlights.js
  src/pages/Main/SearchedTickets/SearchedTickets.js
Labels: Status: 리뷰 요청

#18 [28기 성윤경]Fix : conflict 해결, 국가정보 개선, aside 수정, bgc 수정, layout 개선
  package-lock.json
  package.json
  src/Router.js
  src/components/ReservedFlightTable/ReservedFlightTable.js
  src/config/config.js
  src/pages/Auth/Auth.js
  src/pages/Reservation/PassengerInfo.js
  src/pages/Reservation/ReservAside.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/ReservedTicketInfo.js
  src/pages/Reservation/contriesData.js
Labels: Status: 리뷰 요청

#16 [28기 김선주] Navbar 추가 구현 완료
  src/Router.js
  src/components/Navbar/Navbar.js
  src/index.js
  src/pages/Auth/Auth.js
Labels: Status: 리뷰 요청

#19 [28기 박준영] 로딩 페이지 수정
  src/pages/FlightsList/FlightsList.js
  src/pages/FlightsList/components/FlightLoading.js
Labels: Status: 리뷰 요청
